THISDIR := $(realpath .)

LIBRARY = libcommon.so

CPPFLAGS = 

INCLUDES = \
	-isystem /opt/local/libcpp-software/include \
	-I $(THISDIR)/../ext/include 

LDFLAGS = \
	-L /opt/local/libcpp-software/lib

include ../Makefile.lib