all:
	make -C libcommon
	make -C liboptimizer
	make -C simulation
	make -C libintergdb
	make -C test

clean:
	make -C libcommon clean
	make -C liboptimizer clean
	make -C simulation clean
	make -C libintergdb clean
	make -C test clean


