.PHONY: all clean

all:
	make -C libcommon all
	make -C liboptimizer all
	make -C simulation all
	make -C libintergdb all
	make -C experiments all
	make -C test all

clean:
	make -C libcommon clean
	make -C liboptimizer clean
	make -C simulation clean
	make -C libintergdb clean
	make -C experiments clean
	make -C test clean


